In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv('../Zycus/86b13d9a4b8e11ec/project/training_data.csv')
df.head()
df2=pd.read_csv('../Zycus/86b13d9a4b8e11ec/project/testing_data.csv')

In [3]:
df.category.value_counts().to_frame()

category
None                         10123
Home & Kitchen                4960
Tools & Home Improvement      2080
Office Products               1144
Grocery & Gourmet Food        1102
Industrial & Scientific        588
Electronics                    191

In [4]:
# count_vec = CountVectorizer()
# bow = count_vec.fit_transform(df['title'])
# bow = np.array(bow.todense())

In [5]:
# 1. import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer

# 2. instantiate CountVectorizer (vectorizer)
vect = CountVectorizer()

In [6]:
# 3. fit
# learn the 'vocabulary' of the training data (occurs in-place)
simple_train = df['title'].tolist()

vect.fit(simple_train)

CountVectorizer()

In [7]:
# examine the fitted vocabulary
vect.get_feature_names()

['00',
 '000',
 '0000',
 '00004',
 '00006',
 '0001',
 '00016',
 '0002',
 '00021',
 '00028896',
 '0003',
 '0007',
 '0009',
 '000hr',
 '000mfd',
 '000mm',
 '000uf',
 '001',
 '0010',
 '0012',
 '0015',
 '0016838',
 '0016958',
 '0018',
 '001g155myel',
 '002',
 '0020860nue',
 '002090090512388',
 '0020a',
 '00214000',
 '00224',
 '003',
 '003a',
 '003b',
 '003c',
 '004',
 '00400',
 '0043',
 '00431',
 '00457',
 '00470',
 '0048',
 '005',
 '0051384099',
 '005656',
 '0058',
 '006',
 '00620',
 '00662',
 '0067944',
 '0070a',
 '00743',
 '0077',
 '008',
 '0081',
 '00815a',
 '00835a',
 '008r',
 '009',
 '0090',
 '00911a',
 '0095',
 '00d',
 '00h',
 '00mm',
 '00rb',
 '00w',
 '01',
 '010',
 '0100',
 '01006634',
 '0101',
 '01025a',
 '01081',
 '011',
 '011023256',
 '011057852',
 '0112',
 '011420',
 '011s',
 '012',
 '012189',
 '012c',
 '012hbge',
 '013',
 '0131',
 '013c',
 '014',
 '0141',
 '01420220al2',
 '01470',
 '01472a',
 '01472arl',
 '014973125608',
 '014973181017',
 '014973301385',
 '014973325749',
 '01

In [8]:
# 4. transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<20188x33076 sparse matrix of type '<class 'numpy.int64'>'
	with 222567 stored elements in Compressed Sparse Row format>

In [9]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
# examine the vocabulary and document-term matrix together
# pd.DataFrame(matrix, columns=columns)
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

00  000  0000  00004  00006  0001  00016  0002  00021  00028896  ...  \
0       0    0     0      0      0     0      0     0      0         0  ...   
1       0    0     0      0      0     0      0     0      0         0  ...   
2       0    0     0      0      0     0      0     0      0         0  ...   
3       0    0     0      0      0     0      0     0      0         0  ...   
4       0    0     0      0      0     0      0     0      0         0  ...   
...    ..  ...   ...    ...    ...   ...    ...   ...    ...       ...  ...   
20183   0    0     0      0      0     0      0     0      0         0  ...   
20184   0    0     0      0      0     0      0     0      0         0  ...   
20185   0    0     0      0      0     0      0     0      0         0  ...   
20186   0    0     0      0      0     0      0     0      0         0  ...   
20187   0    0     0      0      0     0      0     0      0         0  ...   

       zwiesel  zwilling  zy  zy1418  zyliss  zytel  zytelhandle  zyxel  zz  \
0            0         0   0       0       0      0            0      0   0   
1            0         0   0       0       0      0            0      0   0   
2            0         0   0       0       0      0            0      0   0   
3            0         0   0       0       0      0            0      0   0   
4            0         0   0       0       0      0            0      0   0   
...        ...       ...  ..     ...     ...    ...          ...    ...  ..   
20183        0         0   0       0       0      0            0      0   0   
20184        0         0   0       0       0      0            0      0   0   
20185        0         0   0       0       0      0            0      0   0   
20186        0         0   0       0       0      0            0      0   0   
20187        0         0   0       0       0      0            0      0   0   

       zzr  
0        0  
1        0  
2        0  
3        0  
4        0  
...    ...  
20183    0  
20184    0  
20185    0  
20186    0  
20187    0  

[20188 rows x 33076 columns]

In [11]:
# check the type of the document-term matrix
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [12]:
# examine the sparse matrix contents
# left: coordinates of non-zero values
# right: values at that point
# CountVectorizer() will output a sparse matrix
print('sparse matrix')
print(simple_train_dtm)

print('dense matrix')
print(simple_train_dtm.toarray())

sparse matrix
  (0, 6581)	1
  (0, 29826)	1
  (0, 29911)	1
  (1, 8368)	1
  (1, 13805)	1
  (1, 14762)	1
  (1, 15674)	1
  (1, 15766)	1
  (1, 16999)	1
  (1, 22718)	1
  (1, 27126)	1
  (1, 28880)	1
  (1, 31462)	1
  (1, 31804)	1
  (2, 729)	1
  (2, 1105)	1
  (2, 8635)	1
  (2, 11048)	1
  (2, 17937)	1
  (2, 19615)	1
  (2, 24289)	1
  (2, 25097)	1
  (2, 27575)	1
  (2, 29178)	1
  (2, 30124)	1
  :	:
  (20186, 17538)	1
  (20186, 17546)	1
  (20186, 17718)	1
  (20186, 19589)	1
  (20186, 21496)	1
  (20186, 21498)	1
  (20186, 22718)	1
  (20186, 23454)	1
  (20186, 24310)	1
  (20186, 24805)	1
  (20186, 26935)	1
  (20186, 29826)	1
  (20186, 32251)	1
  (20187, 6596)	1
  (20187, 6647)	1
  (20187, 9860)	1
  (20187, 12407)	1
  (20187, 14637)	1
  (20187, 18747)	1
  (20187, 19612)	1
  (20187, 19619)	1
  (20187, 21671)	1
  (20187, 26067)	1
  (20187, 30337)	1
  (20187, 31707)	1
dense matrix
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
# example text for model testing
simple_test = df2['title'].tolist()

In [14]:
# 4. transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

00  000  0000  00004  00006  0001  00016  0002  00021  00028896  ...  \
0       0    0     0      0      0     0      0     0      0         0  ...   
1       0    0     0      0      0     0      0     0      0         0  ...   
2       0    0     0      0      0     0      0     0      0         0  ...   
3       0    0     0      0      0     0      0     0      0         0  ...   
4       0    0     0      0      0     0      0     0      0         0  ...   
...    ..  ...   ...    ...    ...   ...    ...   ...    ...       ...  ...   
10089   0    0     0      0      0     0      0     0      0         0  ...   
10090   0    0     0      0      0     0      0     0      0         0  ...   
10091   0    0     0      0      0     0      0     0      0         0  ...   
10092   0    0     0      0      0     0      0     0      0         0  ...   
10093   0    0     0      0      0     0      0     0      0         0  ...   

       zwiesel  zwilling  zy  zy1418  zyliss  zytel  zytelhandle  zyxel  zz  \
0            0         0   0       0       0      0            0      0   0   
1            0         0   0       0       0      0            0      0   0   
2            0         0   0       0       0      0            0      0   0   
3            0         0   0       0       0      0            0      0   0   
4            0         0   0       0       0      0            0      0   0   
...        ...       ...  ..     ...     ...    ...          ...    ...  ..   
10089        0         0   0       0       0      0            0      0   0   
10090        0         0   0       0       0      0            0      0   0   
10091        0         0   0       0       0      0            0      0   0   
10092        0         0   0       0       0      0            0      0   0   
10093        0         0   0       0       0      0            0      0   0   

       zzr  
0        0  
1        0  
2        0  
3        0  
4        0  
...    ...  
10089    0  
10090    0  
10091    0  
10092    0  
10093    0  

[10094 rows x 33076 columns]

In [18]:
df2.category.value_counts().to_frame()

Empty DataFrame
Columns: [category]
Index: []